version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:8000"
    volumes:
      - .:/app
      - ./config/webserver:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    container_name: app_server
    command: gunicorn app:api -c config/gunicorn_config.py
    volumes:
      - .:/app
    expose:
      - "8000"